# FN6815 Numerical Methods for Financial Instrument Pricing

# Lecture 5: Solve Multiple Equations

-   Dr. Yang Ye
-   Email: yy@runchee.com
-   2023/2024 Mini Term 5


## 1. Recap

In the previous lecture, we discussed several methods for solving non-linear equation:

1. **Newton-Raphson method**: This method is used to find roots of $f(x) = 0$ when $f'(x)$ is known.
2. **Secant method**: This method is also used to find roots of $f(x) = 0$, but it doesn't require knowledge of $f'(x)$.
3. **Bisection method**: This method is used to find roots of $f(x) - y = 0$ within a known interval $[a,b]$ where $f(a)f(b)<0$.

### Discussion:

When considering the generalization of these methods to solve a system of equations rather than a single equation, which method is viable?

**Bisection Method**: In n-dimensions, for the bisection method to work, we need to find a range such that $f(\vec{x_a}) \cdot f(\vec{x_b}) < 0$. This can be challenging in higher dimensions.

**Newton's Method**: Newton's method, on the other hand, doesn't require a range but only a starting point. It can be generalized to n-dimensions using Jacobian matrix, making it more suitable for solving systems of equations.


## 2. Solve for Multiple Equations


### 2.1 Solving Linear Equations

**Gaussian Elimination** is a prevalent and robust method for solving systems of linear equations. It systematically reduces the system to a form from which the solution can be directly read.

Python's `numpy` package provides a module `linalg` that includes a function `solve()`. It solves a system of linear equations in the form $Ax=b$. with `x = numpy.linalg.solve(A, b)`.

<div class="alert alert-block alert-success">Question: Which equation below is linear?</div>

1. $3x_1 + 4x_2 - 3 = -5x_3$
2. $\frac{-x_1 + x_2}{x_3} = 2$
3. $x_1x_2 + x_3 = 5$


#### Let's Solve for below linear equations

$\begin{cases}
 3x_1 + 4x_2 - 3 = 0 \\ 
 x_1 + x_2 = 5
\end{cases}$


In [5]:
import numpy as np

A = np.array([[3, 4], [1, 1]])
b = np.array([3, 5])
x = np.linalg.solve(A, b)
print(x)

assert np.allclose(np.dot(A, x), b)

[ 17. -12.]


Alternatively, use inv method, $x = A^{-1}b$.


In [2]:
import numpy as np

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print(x)

assert np.allclose(np.dot(A, x), b)

[ 17. -12.]


### 2.2 Solve Non-linear Equations


#### 2.2.1 Taylor expansions for multi-variable functions

The concept behind Newton's method for solving a single equation can be extended to multiple variables. The idea is to iteratively approximate the nonlinear function $f$ at a point $\mathbf{x}_i$ by a linear function and find its root $\mathbf{x}_{i+1}$. This process is repeated until the root approximation improves insignificantly.

In the case of $n$ variables, we need to approximate a vector function $\mathbf{F}(\vec{\mathbf{x}})$ by some linear function $\tilde{\mathbf{F}} = \mathbf{J}\vec{\mathbf{x}} + \mathbf{c}$. Here, $\mathbf{J}$ is an $n\times n$ matrix (the Jacobian matrix of $\mathbf{F}$), and $\mathbf{c}$ is a vector of length $n$.

How to obtain the linear form of $\mathbf{F}$ at $\vec{\mathbf{x}}_i$? The Taylor series expansion. We use the first two terms of the expansion to form the linear approximation:

$$\mathbf{F}(\vec{\mathbf{x}}) \approx \mathbf{F}(\vec{\mathbf{x}_i}) + \mathbf{J}(\vec{\mathbf{x}_i})(\vec{\mathbf{x}} - \vec{\mathbf{x}_i})$$

This equation represents the linear approximation of $\mathbf{F}$ around the point $\mathbf{x}_i$.

The next terms in the expansions are omitted here and of ths scale
$||\vec{\mathbf{x}}-\vec{\mathbf{x}_i}||^2$, which are assumed to be small and negligible compared with the two terms above.


#### 2.2.2 Jacobian $\nabla$ or $\mathbf{J}$

_Jacobian_ $\mathbf{J}$ of vector function $\mathbf{F}$ is the matrix of all the partial derivatives
of $\mathbf{F}$. Component $(i,j)$ in $\nabla\mathbf{F}$ is

$$
\frac{\partial F_i}{\partial x_j}\thinspace .
$$

For 2-d vector function $\mathbf{F}$, We can then write

$$
\mathbf{J} = \left(\begin{array}{ll}
\frac{\partial F_0}{\partial x_0} & \frac{\partial F_0}{\partial x_1}\\
\frac{\partial F_1}{\partial x_0} & \frac{\partial F_1}{\partial x_1}
\end{array}\right)
$$


#### 2.2.3 Newton's method for n-dimension

The Newton-Raphson method for one dimension is given by:

$$x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)},\quad n=0,1,2,\ldots$$

We can rewrite this as:

$$
f(x_n)+f'(x_n)(x_{n+1} - x_n) = 0
$$

For multiple dimensions, we use the Jacobian matrix to obtain the linear equation at $\mathbf{x}_i$,

$$
\mathbf{F}(\vec{\mathbf{x}}) \approx \mathbf{F}(\vec{\mathbf{x}_i}) + \mathbf{J}(\vec{\mathbf{x}_i})(\vec{\mathbf{x}} - \vec{\mathbf{x}_i})
$$

And then solve for $\mathbf{x}_{i+1}$, by setting $\mathbf{F}(\mathbf{x}_{i+1})=0$.

$$
\mathbf{F}(\vec{\mathbf{x}_i}) + \mathbf{J}(\vec{{x}_i})(\vec{{x}_{i+1}}-\vec{{x}_i}) = {0},
$$

We use symbol $\mathbf{\delta}$ for the the change in $\mathbf{x}$ to the next iteration, $\mathbf{x}_{i+1} = \mathbf{x}_i + \mathbf{\delta}$.

$$\mathbf{J}(\mathbf{x}_i)\mathbf{\delta} = -\mathbf{F}(\mathbf{x}_i),$$

We then go through the iterative process of following steps:

1. Solve the linear system $\mathbf{J}(\mathbf{x}_i)\mathbf{\delta} = -\mathbf{F}(\mathbf{x}_i)$ to find $\mathbf{\delta}$.
2. Update the estimate: $\mathbf{x}_{i+1} = \mathbf{x}_i + \mathbf{\delta}$.
3. Check the exit condition: if the norm of $\mathbf{F}(\mathbf{x}_i)$ is sufficiently small, exit the loop.
   Because $\mathbf{F}(\mathbf{x}_i)$ is a vector, we use `linalg.norm` to check all its values are close to zero.


Here's a simple Python example using the Newton's method for a system of equations:


In [6]:
from typing import Callable

import numpy as np
import numpy.typing as npt

print(npt.NDArray)


def Newton_system(F: Callable, J: Callable, x: npt.NDArray, eps: float):
    """
    Solve nonlinear system F=0 by Newton's method.

    J is the Jacobian of F.
    Both F and J must be functions of x.
    x holds the start value.
    The iteration continues until ||F|| < eps.
    """
    F_value = F(x)
    F_norm = np.linalg.norm(F_value, ord=2)  # l2 norm of vector
    iteration_counter = 0
    while abs(F_norm) > eps and iteration_counter < 100:
        # Inverse is more expensive calculation than solving
        # Use inverse for simple verification only
        # Inverse: delta = np.matmul(np.linalg.inv(J(x)), -F_value)
        if F_value.shape == (1,):
            delta = 1 / J(x) * -F_value
        else:
            delta = np.linalg.solve(J(x), -F_value)
        x = x + delta
        F_value = F(x)
        F_norm = np.linalg.norm(F_value, ord=2)
        iteration_counter += 1

    # Here, either a solution is found, or too many iterations
    if abs(F_norm) > eps:
        return None, iteration_counter
    return x, iteration_counter


def test_Newton_system1(F, J, expected, start_x, tol=1e-4):
    x, n = Newton_system(F, J, x=start_x, eps=tol)
    print(f"x={x}, n={n}")
    error_norm = np.linalg.norm(expected - x, ord=2)
    assert error_norm < tol, "norm of error =%g" % error_norm
    print("norm of error =%g" % error_norm)

numpy.ndarray[typing.Any, numpy.dtype[+_ScalarType_co]]


### 2.3 Try it Out

#### 2.3.1 1-D linear system

$$
\begin{aligned}
y & = 3x + 3 \\
\frac {\mathrm{d}y} {\mathrm{d}x} & = 3
\end{aligned}
$$


In [7]:
# We can test the function Newton_system with the 2×2 system (172)-(173):
F = lambda x: np.array(
    [
        3 * x + 3,
    ]
)
J = lambda _x: np.array([3])

test_Newton_system1(F, J, expected=np.array(-1), start_x=np.array(100))
# Linear function's n == 1

x=[-1.], n=1
norm of error =0


#### 2.3.2 2-D linear system


In [8]:
A = np.array([[3, 4], [1, 1]])
b = np.array([3, 5])
x = np.linalg.solve(A, b)
print(x)

[ 17. -12.]


In [6]:
# Use Newton's method
F = lambda x: np.array([3 * x[0] + 4 * x[1] - 3, 1 * x[0] + 1 * x[1] - 5])
J = lambda _x: np.array([[3, 4], [1, 1]])

test_Newton_system1(F, J, expected=np.array([17, -12]), start_x=np.array([1, 2]))
# For linear function's n == 1

x=[ 17. -12.], n=1
norm of error =3.97205e-15


#### 2.3.3 Non-linear Equations


Let's solve for below non-linear equations

$$
\begin{cases}
y = 3x + sin(x)^2 \\
y^2 = cos(x)
\end{cases}
$$


In [7]:
def F(x):
    x0, x1 = x[0], x[1]
    return np.array([x1 - 3 * x0 - np.sin(x0) ** 2, x1**2 - np.cos(x0)])


def J(x):
    x0, x1 = x[0], x[1]
    return np.array([[-2 * np.sin(x0) * np.cos(x0) - 3, 1], [np.sin(x0), 2 * x1]])


expected = np.array(
    [-0.36456854, -0.96658041],
)
test_Newton_system1(F, J, expected, start_x=np.array([2.0, -1.0]), tol=1e-8)
F([-0.36456854, -0.96658041])

x=[-0.36456854 -0.96658041], n=6
norm of error =2.83469e-09


array([-1.05223608e-11,  5.44045708e-09])

### 2.4 Summary

To solve for n-dimensional non-linear equation, Newton's method has the advantage of speed and convergence. The method requires the Jacobian matrix of the function, and iteratively updates the estimate of the root until the function value is close to zero.

The Newton's method for solving systems of equations in vector form is given by:

$$\vec{x}_{n+1} = \vec{x}_n - [J(\vec{x}_n)]^{-1} \cdot \vec{f}(\vec{x}_n)$$

In this equation, $\vec{x}_n$ is the current estimate of the solution, $J(\vec{x}_n)$ is the Jacobian matrix evaluated at $\vec{x}_n$, and $\vec{f}(\vec{x}_n)$ is the vector function evaluated at $\vec{x}_n$. The term $[J(\vec{x}_n)]^{-1} \cdot \vec{f}(\vec{x}_n)$ represents the step taken in the direction of the solution.


## 3. Assignment

### Q1. Gradient Descent

Gradient Descent, a first-order iterative optimization algorithm, is used to find a local minimum of a differentiable function. It's built on Newton's method and was first suggested by Augustin-Louis Cauchy in 1847. Jacques Hadamard independently proposed a similar method in 1907.

The algorithm uses the Jacobian matrix at position $\bar{x}_n$ to iteratively update $\bar{x}_{n+1}$, aiming to reach a local or global minimum. The learning rate, denoted as $\eta$, influences the step size in each iteration:

$$\bar{x}{n+1} = \bar{x}{n} - J * \eta$$

The learning rate must be carefully chosen. If it's too large, the algorithm may oscillate around the minimum. If it's too small, the convergence may be slow.

Consider the unimodal function $z^2 = (x - x_c)^2 + (y - y_c)^2$ with $x_c = 2$ and $y_c = -1$. We want to find the minimum of this function using gradient descent.

Here's a prototype for the Python function solve() that implements the gradient descent algorithm:

```python
def solve(xs_init, _f_func, _j_func, ...)
```

In this function, `xs_init` is the initial guess, `_f_func` is the function to minimize, `_j_func` is the Jacobian of `_f_func`, `learning_rate` is the learning rate, and `precision` is the desired precision of the result be reached.

You can experiment with different learning rates and initial guesses to observe the behavior of the algorithm. while

Find two set of parameters such that

1. Not able to find the answer with whatever number of steps.
2. A suitable learning rate and initial guess can help the algorithm find the minimum $(2, -1)$ within $0.01$ precision.


In [7]:
import numpy as np

# Define the function to minimize and its Jacobian
def f_func(z, x_c=2, y_c=-1):
    x, y = z
    return (x - x_c)**2 + (y - y_c)**2

def j_func(z, x_c=2, y_c=-1):
    x, y = z
    return np.array([2*(x - x_c), 2*(y - y_c)])

# Define the gradient descent solver
def solve(xs_init, f_func, j_func, learning_rate, precision):
    x_current = np.array(xs_init)
    iteration = 0
    x_history = [x_current]

    while True:
        jacobian = j_func(x_current)
        x_next = x_current - learning_rate * jacobian

        # Store the history of x values
        x_history.append(x_next)
        
        # Check if the precision condition is met
        if np.linalg.norm(x_next - x_current) < precision:
            break

        x_current = x_next
        iteration += 1

    return x_next, iteration, x_history

# Example usage of the solve function with a learning rate that is too high and low precision
high_learning_rate = 1
low_precision = 10

# Example usage of the solve function with a suitable learning rate and precision
suitable_learning_rate = 0.01
suitable_precision = 0.00001

# Try the function with both sets of parameters
high_lr_result = solve((0, 0), f_func, j_func, high_learning_rate, low_precision)
suitable_lr_result = solve((0, 0), f_func, j_func, suitable_learning_rate, suitable_precision)

high_lr_result, suitable_lr_result


((array([ 4, -2]), 0, [array([0, 0]), array([ 4, -2])]),
 (array([ 1.99956994, -0.99978497]),
  417,
  [array([0, 0]),
   array([ 0.04, -0.02]),
   array([ 0.0792, -0.0396]),
   array([ 0.117616, -0.058808]),
   array([ 0.15526368, -0.07763184]),
   array([ 0.19215841, -0.0960792 ]),
   array([ 0.22831524, -0.11415762]),
   array([ 0.26374893, -0.13187447]),
   array([ 0.29847395, -0.14923698]),
   array([ 0.33250448, -0.16625224]),
   array([ 0.36585439, -0.18292719]),
   array([ 0.3985373 , -0.19926865]),
   array([ 0.43056655, -0.21528328]),
   array([ 0.46195522, -0.23097761]),
   array([ 0.49271612, -0.24635806]),
   array([ 0.52286179, -0.2614309 ]),
   array([ 0.55240456, -0.27620228]),
   array([ 0.58135647, -0.29067823]),
   array([ 0.60972934, -0.30486467]),
   array([ 0.63753475, -0.31876738]),
   array([ 0.66478406, -0.33239203]),
   array([ 0.69148838, -0.34574419]),
   array([ 0.71765861, -0.3588293 ]),
   array([ 0.74330544, -0.37165272]),
   array([ 0.76843933, -0.38421

In [4]:
suitable_lr_result

(array([ 1.56926343, -0.78463171]),
 75,
 [array([0, 0]),
  array([ 0.04, -0.02]),
  array([ 0.0792, -0.0396]),
  array([ 0.117616, -0.058808]),
  array([ 0.15526368, -0.07763184]),
  array([ 0.19215841, -0.0960792 ]),
  array([ 0.22831524, -0.11415762]),
  array([ 0.26374893, -0.13187447]),
  array([ 0.29847395, -0.14923698]),
  array([ 0.33250448, -0.16625224]),
  array([ 0.36585439, -0.18292719]),
  array([ 0.3985373 , -0.19926865]),
  array([ 0.43056655, -0.21528328]),
  array([ 0.46195522, -0.23097761]),
  array([ 0.49271612, -0.24635806]),
  array([ 0.52286179, -0.2614309 ]),
  array([ 0.55240456, -0.27620228]),
  array([ 0.58135647, -0.29067823]),
  array([ 0.60972934, -0.30486467]),
  array([ 0.63753475, -0.31876738]),
  array([ 0.66478406, -0.33239203]),
  array([ 0.69148838, -0.34574419]),
  array([ 0.71765861, -0.3588293 ]),
  array([ 0.74330544, -0.37165272]),
  array([ 0.76843933, -0.38421966]),
  array([ 0.79307054, -0.39653527]),
  array([ 0.81720913, -0.40860456]),
  ar

##### Appendix: timestamp


In [8]:
from datetime import datetime

print(f"Generated on {datetime.now()}")

Generated on 2024-03-01 22:12:24.262064
